
Avec NumPy — empiler plusieurs tableaux

## vstack (vertical stack) empile les lignes les unes sous les autres — utile quand les fichiers ont les mêmes colonnes (mêmes modules) mais des étudiants différents

In [9]:
import pandas as pd
import matplotlib.pyplot as plt


df_ia = pd.read_csv('data/notes_filiere_ia.csv')
df_reseaux = pd.read_csv('data/notes_filiere_reseaux.csv')

df_toutes_filieres = pd.concat([df_ia, df_reseaux], ignore_index=True)

df_toutes_filieres.shape

(100, 6)

In [15]:
df_ia.isnull()

,id_etudiant,filiere,Machine_Learning,Fouille_de_donnees,Bases_de_donnees,Statistiques
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,False,False,False,False,False
51,False,False,False,False,False,False
52,False,False,False,False,False,False
53,False,False,False,False,False,False
54,False,False,False,False,False,False
55,False,False,False,False,False,False
56,False,False,False,False,False,False
57,False,False,False,False,False,False
58,False,False,False,False,False,False
59,False,False,False,False,False,False

In [14]:
df_ia.shape

(60, 6)

In [ ]:
df_toutes_filieres.info

<bound method DataFrame.info of    id_etudiant  filiere  Machine_Learning  Fouille_de_donnees  \
0        IA001       IA                11                  11
1        IA002       IA                 8                   6
2        IA003       IA                17                   8
3        IA004       IA                19                  13
4        IA005       IA                15                  16
..         ...      ...               ...                 ...
95       RS036  Reseaux                 5                  15
96       RS037  Reseaux                12                  10
97       RS038  Reseaux                 5                  17
98       RS039  Reseaux                15                   7
99       RS040  Reseaux                 5                   8

    Bases_de_donnees  Statistiques
0                 14            11
1                 13            19
2                 16            18
3                 16            11
4                 16            15
..               ...           ...
95                 6            17
96                 5            13
97                18             8
98                16             5
99                 9             8

[100 rows x 6 columns]>

Detection des  elements abscents

In [12]:
df_toutes_filieres.isnull()

,id_etudiant,filiere,Machine_Learning,Fouille_de_donnees,Bases_de_donnees,Statistiques
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
95,False,False,False,False,False,False
96,False,False,False,False,False,False
97,False,False,False,False,False,False
98,False,False,False,False,False,False
99,False,False,False,False,False,False

In [13]:
df_toutes_filieres.head

<bound method NDFrame.head of    id_etudiant  filiere  Machine_Learning  Fouille_de_donnees  \
0        IA001       IA                11                  11
1        IA002       IA                 8                   6
2        IA003       IA                17                   8
3        IA004       IA                19                  13
4        IA005       IA                15                  16
..         ...      ...               ...                 ...
95       RS036  Reseaux                 5                  15
96       RS037  Reseaux                12                  10
97       RS038  Reseaux                 5                  17
98       RS039  Reseaux                15                   7
99       RS040  Reseaux                 5                   8

    Bases_de_donnees  Statistiques
0                 14            11
1                 13            19
2                 16            18
3                 16            11
4                 16            15
..               ...           ...
95                 6            17
96                 5            13
97                18             8
98                16             5
99                 9             8

[100 rows x 6 columns]>